language: java
jdk:
 - oraclejdk8
script:
 - mvn clean install
deploy:
  provider: releases
  api_key: ${GH_TOKEN_OXYGEN}
  file: 
    - target/git.support-1.0.0-plugin.jar
    - target/addon.xml
  
  skip_cleanup: true
  on:
    tags: true
